modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/gulab9762/quick-craft/issues"

[[mods]]
modId="quick-craft"
version="${file.jarVersion}"
displayName="Quick Craft"
displayURL="https://modrinth.com/mod/quickcraft"
logoFile="icon.png"
authors="IGxxD!"
description='''
Mod to get desired enchantment book trade from librarian villager
'''

[[dependencies.quick-craft]]
    modId="forge"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quick-craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"
